apps/subscriptions/urls.py
from django.urls import path

from . import views


app_name = 'subscriptions'
urlpatterns = [
    path('api/active-products/', views.ProductWithMetadataAPI.as_view(), name='products_api'),

    # user-specific URLs
    path('', views.subscription, name='subscription_details'),
    path('intelgroup/<int:groupid>', views.subscription, name='subscription_intelgroup'),
    path('subscription_success/', views.subscription_success, name='subscription_success'),
    path('demo/', views.subscription_demo, name='subscription_demo'),
    path('subscription-gated-page/', views.subscription_gated_page, name='subscription_gated_page'),
    path('stripe-portal/', views.create_stripe_portal_session, name='create_stripe_portal_session'),
    path('api/create_customer/', views.create_customer, name='create_customer'),
    path('api/update_customer/', views.update_customer, name='update_customer'),

]

apps/users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path(r'profile/', views.profile, name='user_profile'),
    path(r'profile/upload-image/', views.upload_profile_image, name='upload_profile_image'),
]

apps/web/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'web'
urlpatterns = [
    path(r'', views.home, name='home'),
    path(r'grouplist', views.grouplist, name='grouplist'),

    path(r'terms', TemplateView.as_view(template_name="web/terms.html"), name='terms'),

]

pega/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.documentation import include_docs_urls, get_schemajs_view
from rest_framework import routers
from project import views
from django.conf.urls import url
# from rest_framework_swagger.views import get_swagger_view
from project.api.swagger import get_swagger_view
# from two_factor.urls import urlpatterns as tf_urls
# from two_factor.gateways.twilio.urls import urlpatterns as tf_twilio_urls

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

schema_views = get_swagger_view(title='API')
schemajs_view = get_schemajs_view(title="API")


urlpatterns = [
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^api/docs/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    # url(r'', include(tf_urls)),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('users/', include('apps.users.urls')),
    path('subscriptions/', include('apps.subscriptions.urls')),


    # path('', include('project.urls')),
    # url(r'api/docs', schema_views),
    path('app/', include('project.urls')),
    path('api/', include('project.api.urls')),
    path('', include('apps.web.urls')),
    path('pegasus/', include('pegasus.apps.examples.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    # API docs
    # these are needed for schema.js
    path('docs/', include_docs_urls(title='API Docs')),
    path('schemajs/', schemajs_view, name='api_schemajs'),
    path("stripe/", include("djstripe.urls", namespace="djstripe")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
router = routers.DefaultRouter()
urlpatterns += router.urls

pegasus/apps/examples/urls.py
from django.urls import path
from django.views.generic import TemplateView
from rest_framework import routers

from . import views


app_name = 'pegasus_examples'

urlpatterns = [
    path(r'', views.ExamplesHomeView.as_view(), name='examples_home'),
    path(r'payments', views.PaymentView.as_view(), name='payments'),
    path(r'payments/create/', views.accept_payment, name='accept_payment'),
    path(r'payments/confirm/<slug:payment_id>/', views.payment_confirm, name='payment_confirm'),
    path(r'landing_page/', TemplateView.as_view(template_name='pegasus/examples/example_landing_page.html'),
         name='landing_page'),
    path(r'pricing_page/', TemplateView.as_view(template_name='pegasus/examples/example_pricing_page.html'),
         name='pricing_page'),
    path(r'objects/react/', views.ReactObjectLifecycleView.as_view(), name='react_object_lifecycle'),
    path(r'objects/react/<path:path>', views.ReactObjectLifecycleView.as_view(), name='react_object_lifecycle_w_path'),
    path(r'objects/vue/', views.VueObjectLifecycleView.as_view(), name='vue_object_lifecycle'),
    path(r'charts/', views.ChartsView.as_view(), name='charts'),
    path(r'tasks/', views.TasksView.as_view(), name='tasks'),
    path(r'tasks/api/', views.tasks_api, name='tasks_api'),

    path(r'api/employee-data/', views.EmployeeDataAPIView.as_view(), name='employee_data'),
]


# drf config
router = routers.DefaultRouter()
router.register(r'api/employees', views.EmployeeViewSet)

urlpatterns += router.urls

templates/web/components/app_nav.html
<aside class="menu">
  <p class="menu-label is-hidden-tablet-only">
    Application
  </p>
  <ul class="menu-list">
      <li>
          <a href="{% url 'web:home' %}" {% if active_tab == 'dashboard' %}class="is-active"{% endif %}>
              <span class="icon"><i class="fa fa-home"></i></span><span class="is-hidden-tablet-only">Dashboard</span>
          </a>
      </li>



    <li>
      <a href="{% url 'subscriptions:subscription_demo' %}" {% if active_tab == 'subscription_demo' %}class="is-active"{% endif %}>
          <span class="icon"><i class="fa fa-desktop"></i></span><span class="is-hidden-tablet-only">Subscription Demo</span>
      </a>
    </li>


  </ul>
  <p class="menu-label is-hidden-tablet-only">
    My Account
  </p>
  <ul class="menu-list">

    <li>
        <a href="{% url 'subscriptions:subscription_details' %}" {% if active_tab == 'subscription' %}class="is-active"{% endif %}>
            <span class="icon"><i class="fa fa-repeat"></i></span><span class="is-hidden-tablet-only">Subscription</span>
        </a>
    </li>


    <li>
        <a href="{% url 'users:user_profile' %}" {% if active_tab == 'profile' %}class="is-active"{% endif %}>
            <span class="icon"><i class="fa fa-user"></i></span><span class="is-hidden-tablet-only">Profile</span>
        </a>
    </li>
    {% if user.has_usable_password %}
    <li>
        <a href="{% url 'account_change_password' %}" {% if 'accounts/password/change' in request.path %}class="is-active"{% endif %}>
            <span class="icon"><i class="fa fa-unlock-alt"></i></span><span class="is-hidden-tablet-only">Change Password</span>
        </a>
    </li>
    {% endif %}
    <li>
        <a href="{% url 'account_logout' %}" {% if 'accounts/logout' in request.path %}class="is-active"{% endif %}>
            <span class="icon"><i class="fa fa-sign-out"></i></span><span class="is-hidden-tablet-only">Sign out</span>
        </a>
    </li>
  </ul>


</aside>

templates/web/components/favicon.html
{% load static %}
{# see https://realfavicongenerator.net #}
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicons/apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicons/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicons/favicon-16x16.png' %}">
<link rel="manifest" href="{% static 'images/favicons/site.webmanifest' %}">
<link rel="mask-icon" href="{% static 'images/favicons/safari-pinned-tab.svg' %}" color="#5bbad5">
<link rel="shortcut icon" href="{% static 'images/favicons/favicon.ico' %}">
<meta name="msapplication-TileColor" content="#603cba">
<meta name="msapplication-config" content="{% static 'images/favicons/browserconfig.xml' %}">
<meta name="theme-color" content="#ffffff">

templates/web/components/footer.html
<footer class="footer">
  <div class="content has-text-centered">
    <p>
      {{project_meta.NAME}} &mdash; Copyright <span id="copyright-year">2019</span>
    </p>
  </div>
</footer>
<script>
    document.getElementById('copyright-year').innerText = (new Date()).getFullYear();
</script>

templates/web/components/google_analytics.html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id={{ GOOGLE_ANALYTICS_ID  }}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '{{ GOOGLE_ANALYTICS_ID  }}');
</script>

templates/web/components/messages-js.html
<script type="application/javascript">
    document.addEventListener('DOMContentLoaded', () => {
      (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
        let $notification = $delete.parentNode;
        $delete.addEventListener('click', () => {
          $notification.parentNode.removeChild($notification);
        });
      });
    });
</script>

templates/web/components/messages.html
{% if messages %}
    {% for message in messages %}
    <section class="app-message notification {% if message.tags %}is-{% if message.level_tag == 'error' %}danger{% else %}{{ message.level_tag }}{% endif %}{% endif %} {{ message.extra_tags }}" >
        <button class="delete"></button>
        {{ message }}
    </section>
    {% endfor %}
{% endif %}

templates/web/components/meta.html
{% load meta_tags %}
{% load static %}
{% if project_meta %}
{% with project_meta|get_title:page_title as title %}
{% with project_meta|get_description:page_description as description %}
{% with project_meta|get_image_url:page_image as image %}
    <title>{{ title }}</title>
    <meta name="description" content="{{ description }}">
    <meta name="keywords" content="{{ project_meta.KEYWORDS }}">
{% endwith %}
{% endwith %}
{% endwith %}
{% endif %}

templates/web/components/navbar-js.html
<script type="application/javascript">
    // see: https://bulma.io/documentation/components/navbar/
    document.addEventListener('DOMContentLoaded', () => {
        // Get all "navbar-burger" elements
        const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);
        // Check if there are any navbar burgers
        if ($navbarBurgers.length > 0) {
            // Add a click event on each of them
            $navbarBurgers.forEach(el => {
                el.addEventListener('click', () => {
                    // Get the target from the "data-target" attribute
                    const target = el.dataset.target;
                    const $target = document.getElementById(target);

                    // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
                    el.classList.toggle('is-active');
                    $target.classList.toggle('is-active');
                });
            });
        }
    });
</script>

templates/web/components/team_nav.html
{% load team_tags %}
{% if request.team and request.user|is_admin_of:request.team %}
  <li>
      <a href="{% url 'web:team_admin' request.team.slug %}" {% if active_tab == 'team-admin' %}class="is-active"{% endif %}>
          <span class="icon"><i class="fa fa-gear"></i></span><span class="is-hidden-tablet-only">Admin</span>
      </a>
  </li>


  <li>
      <a href="{% url 'subscriptions:team_subscription_demo' request.team.slug %}" {% if active_tab == 'subscription_demo' %}class="is-active"{% endif %}>
          <span class="icon"><i class="fa fa-desktop"></i></span><span class="is-hidden-tablet-only">Subscription Demo</span>
      </a>
  </li>
  <li>
      <a href="{% url 'subscriptions:team_subscription_details' request.team.slug %}" {% if active_tab == 'subscription' %}class="is-active"{% endif %}>
          <span class="icon"><i class="fa fa-repeat"></i></span><span class="is-hidden-tablet-only">Subscription</span>
      </a>
  </li>


{% endif %}

templates/web/components/top_nav.html
<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="container">
      <div class="navbar-brand">
        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="nav-menu">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div class="navbar-menu" id="nav-menu">
        <div class="navbar-start">
          <!--add additional links here if you want-->
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-item" href="/grouplist" >
              <span>Intel Group List</span>
            </a>
          </div>
          {% if user.is_authenticated %}
            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">
                <span>View intel</span>
              </a>
              <div class="navbar-dropdown is-left">
                <a class="navbar-item" href="/app/feedlist" >
                  <span>Feed List</span>
                </a>
                <a class="navbar-item" href="/app/intelreports" >
                  <span>Intel Reports</span>
                </a>
              </div>
            </div>
            
          {% endif %}
        </div>
        <div class="navbar-end">
          {% if user.is_authenticated %}
            <!-- <a class="navbar-item {% if '/pegasus/' in request.path %}is-active{% endif %}" href="{% url 'pegasus_examples:examples_home' %}">
                Examples Gallery
            </a> -->
            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">
                <!-- <img class="avatar is-hidden-touch" src="{{ user.avatar_url}}"> -->
                <span>My Account</span>
              </a>
              <div class="navbar-dropdown is-right">
                <a class="navbar-item" href="/app/account" >
                  <span class="icon"><i class="fa fa-user"></i></span><span>Profile</span>
                </a>
                {% if user.has_usable_password %}
                <a class="navbar-item" href="{% url 'account_change_password' %}">
                  <span class="icon"><i class="fa fa-unlock-alt"></i></span><span>Change Password</span>
                </a>
                {% endif %}
                <a class="navbar-item" href="{% url 'account_logout' %}" >
                  <span class="icon"><i class="fa fa-sign-out"></i></span><span>Sign out</span>
                </a>
              </div>
            </div>
          {% else %}
              <div class="navbar-item">
                  <div class="buttons">
                      <a class="button is-primary is-outlined" href="{% url 'account_signup' %}">Sign up</a>
                      <a class="button is-text" href="{% url 'account_login' %}">Sign in</a>
                  </div>
              </div>
          {% endif %}
        </div>
      </div>
    </div>
</nav>