apps/web/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'web'
urlpatterns = [
    path(r'', views.home, name='home'),
    path(r'grouplist', views.grouplist, name='grouplist'),

    path(r'terms', TemplateView.as_view(template_name="web/terms.html"), name='terms'),

]

pega/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.documentation import include_docs_urls, get_schemajs_view
from rest_framework import routers
from project import views
from django.conf.urls import url
# from rest_framework_swagger.views import get_swagger_view
from project.api.swagger import get_swagger_view
# from two_factor.urls import urlpatterns as tf_urls
# from two_factor.gateways.twilio.urls import urlpatterns as tf_twilio_urls

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

schema_views = get_swagger_view(title='API')
schemajs_view = get_schemajs_view(title="API")


urlpatterns = [
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^api/docs/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    # url(r'', include(tf_urls)),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('users/', include('apps.users.urls')),
    path('subscriptions/', include('apps.subscriptions.urls')),


    # path('', include('project.urls')),
    # url(r'api/docs', schema_views),
    path('app/', include('project.urls')),
    path('api/', include('project.api.urls')),
    path('', include('apps.web.urls')),
    path('pegasus/', include('pegasus.apps.examples.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    # API docs
    # these are needed for schema.js
    path('docs/', include_docs_urls(title='API Docs')),
    path('schemajs/', schemajs_view, name='api_schemajs'),
    path("stripe/", include("djstripe.urls", namespace="djstripe")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
router = routers.DefaultRouter()
urlpatterns += router.urls

pegasus/apps/examples/urls.py
from django.urls import path
from django.views.generic import TemplateView
from rest_framework import routers

from . import views


app_name = 'pegasus_examples'

urlpatterns = [
    path(r'', views.ExamplesHomeView.as_view(), name='examples_home'),
    path(r'payments', views.PaymentView.as_view(), name='payments'),
    path(r'payments/create/', views.accept_payment, name='accept_payment'),
    path(r'payments/confirm/<slug:payment_id>/', views.payment_confirm, name='payment_confirm'),
    path(r'landing_page/', TemplateView.as_view(template_name='pegasus/examples/example_landing_page.html'),
         name='landing_page'),
    path(r'pricing_page/', TemplateView.as_view(template_name='pegasus/examples/example_pricing_page.html'),
         name='pricing_page'),
    path(r'objects/react/', views.ReactObjectLifecycleView.as_view(), name='react_object_lifecycle'),
    path(r'objects/react/<path:path>', views.ReactObjectLifecycleView.as_view(), name='react_object_lifecycle_w_path'),
    path(r'objects/vue/', views.VueObjectLifecycleView.as_view(), name='vue_object_lifecycle'),
    path(r'charts/', views.ChartsView.as_view(), name='charts'),
    path(r'tasks/', views.TasksView.as_view(), name='tasks'),
    path(r'tasks/api/', views.tasks_api, name='tasks_api'),

    path(r'api/employee-data/', views.EmployeeDataAPIView.as_view(), name='employee_data'),
]


# drf config
router = routers.DefaultRouter()
router.register(r'api/employees', views.EmployeeViewSet)

urlpatterns += router.urls

pegasus/apps/examples/models/objects.py
from django.conf import settings
from django.db import models

from apps.utils.models import BaseModel


class Employee(BaseModel):
    DEPARTMENT_CHOICES = (
        ('hr', 'Human Resources'),
        ('finance', 'Finance'),
        ('engineering', 'Engineering'),
        ('marketing', 'Marketing'),
        ('sales', 'Sales'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='employees')
    name = models.CharField(max_length=100)
    department = models.CharField(max_length=20, choices=DEPARTMENT_CHOICES)
    salary = models.PositiveIntegerField()

    def __str__(self):
        return self.name

pegasus/apps/examples/models/payments.py
import uuid

from django.conf import settings
from django.db import models

from apps.utils.models import BaseModel


class Payment(BaseModel):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    charge_id = models.CharField(max_length=100, help_text='The stripe charge ID associated with this payment.')
    name = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='pegasus_payments')
    amount = models.PositiveIntegerField(help_text='In cents')

    @property
    def payment_id(self):
        return str(self.id)

    @property
    def amount_display(self):
        return '${:,.2f}'.format(self.amount / 100.)

pegasus/apps/examples/views/objects.py
from django.contrib.auth.decorators import login_required
from django.db.models import Avg, Sum, Count
from django.templatetags.static import static
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.views import APIView

from ..models import Employee
from ..serializers import EmployeeSerializer


@method_decorator(login_required, name='dispatch')
class ObjectLifecycleView(TemplateView):
    def get_context_data(self, **kwargs):
        return {
            'department_choices': [{
                'id': c[0],
                'name': c[1]
            } for c in Employee.DEPARTMENT_CHOICES],
        }


class ReactObjectLifecycleView(ObjectLifecycleView):
    template_name = 'pegasus/examples/objects/react_object_lifecycle.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'framework_url': 'https://reactjs.org/',
            'framework_name': 'React',
            'framework_icon': static('images/pegasus/react-icon.png'),
            'active_tab': 'react_object_lifecycle',
        })
        return context


class VueObjectLifecycleView(ObjectLifecycleView):
    template_name = 'pegasus/examples/objects/vue_object_lifecycle.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'framework_url': 'https://vuejs.org/',
            'framework_name': 'Vue.js',
            'framework_icon': static('images/pegasus/vue-icon.png'),
            'active_tab': 'vue_object_lifecycle',
        })
        return context


@method_decorator(login_required, name='dispatch')
class ChartsView(TemplateView):
    template_name = 'pegasus/examples/objects/charts.html'

    def get_context_data(self, **kwargs):
        return {
            'active_tab': 'charts',
        }


class EmployeeDataAPIView(APIView):

    def get(self, request):
        data = request.user.employees.values('department').annotate(
            average_salary=Avg('salary'),
            total_cost=Sum('salary'),
            number_employees=Count('pk'),
        )
        # data will look something like this:
        # [
        #     {'total_cost': 132000, 'number_employees': 2, 'average_salary': 66000.0, 'department': 'hr'},
        #     {'total_cost': 60000, 'number_employees': 1, 'average_salary': 60000.0, 'department': 'marketing'}
        # ]
        total_costs = [
            [row['department'], row['total_cost']] for row in data
        ]
        average_salaries = [
            [row['department'], row['average_salary']] for row in data
        ]
        headcounts = [
            [row['department'], row['number_employees']] for row in data
        ]
        return Response({
            'total_costs': total_costs,
            'average_salaries': average_salaries,
            'headcounts': headcounts,
        })


class EmployeeViewSet(viewsets.ModelViewSet):
    queryset = Employee.objects.all()
    serializer_class = EmployeeSerializer

    def get_queryset(self):
        # filter queryset based on logged in user
        return self.request.user.employees.all()

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

pegasus/apps/examples/views/payments.py
import stripe
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView

from apps.utils.decorators import catch_stripe_errors
from ..models import Payment

EXPECTED_PAYMENT_AMOUNT = 2500  # in cents

@method_decorator(login_required, name='dispatch')
class PaymentView(TemplateView):
    template_name = 'pegasus/examples/payments/payments.html'

    def get_context_data(self, **kwargs):
        return {
            'stripe_key': settings.STRIPE_TEST_PUBLIC_KEY,
            'payments': self.request.user.pegasus_payments.all(),
            'amount': EXPECTED_PAYMENT_AMOUNT,
            'active_tab': 'payments',
        }


@login_required
def payment_confirm(request, payment_id):
    """
    Confirmation page after making a payment.
    """
    payment = get_object_or_404(Payment, user=request.user, id=payment_id)
    return render(request, 'pegasus/examples/payments/payment_confirm.html', {
        'payment': payment,
        'active_tab': 'payments',
    })


@login_required
@require_POST
@catch_stripe_errors
def accept_payment(request):
    """
    Accept a payment with a token from Stripe
    """
    amount = int(request.POST['amount'])

    # since this value is coming from the front-end, we need to double-check it is correct
    if amount != EXPECTED_PAYMENT_AMOUNT:
        raise ValueError('Received unexpected payment amount {}'.format(amount))

    name = request.POST['name']
    print(name)
    token = request.POST['stripeToken']
    print(token)
    stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
    user = request.user
    email = request.user.email
    charge = stripe.Charge.create(
        amount=amount,
        currency="usd",
        description=name,
        source=token,
        receipt_email=email,
    )
    payment = Payment.objects.create(
        charge_id=charge.id,
        amount=charge.amount,
        name=name,
        user=user,
    )
    return HttpResponseRedirect(reverse('pegasus_examples:payment_confirm', args=[payment.payment_id]))

pegasus/apps/examples/views/tasks.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView

from ..tasks import progress_bar_task


@method_decorator(login_required, name='dispatch')
class TasksView(TemplateView):
    template_name = 'pegasus/examples/tasks.html'

    def get_context_data(self, **kwargs):
        return {
            'active_tab': 'tasks',
        }


@require_POST
def tasks_api(request):
    result = progress_bar_task.delay(5)
    return HttpResponse(result.task_id)

templates/pegasus/examples/payments/payment_confirm.html
{% extends "pegasus/examples/examples_base.html" %}
{% load static %}
{% block app %}
<section class="section app-card">
    <div class="columns columns-reversed">
        <div class="column">
            <img src="{% static 'images/undraw/undraw_to_the_stars.svg' %}" alt="You're Off!">
        </div>
        <div id="tagline" class="column">
            <h1 class="title is-size-2">Hooray!</h1>
            <h2 class="subtitle is-size-4">
                You just completed a sample payment.<br>Wasn't that easy?
            </h2>
            <p class="has-text-grey">
                To see your shiny new payment or make another, you can head back to the
                <a href="{% url 'pegasus_examples:payments' %}">payments demo</a>.
            </p>
        </div>
    </div>
</section>
{% endblock %}

templates/pegasus/examples/payments/payments.html
{% extends "pegasus/examples/examples_base.html" %}
{% block page_head %}
  <script src="https://js.stripe.com/v3/"></script>
{% endblock %}
{% load static %}
{% block app %}
  <section class="section app-card">
    <div class="columns">
      <div class="column is-one-third">
        <div class="content">
          <h2>Payment Example</h2>
          <p>
            This example provides an end-to-end workflow for collecting payments using Stripe Elements.
          </p>
          <p>
            You can use any <a href="https://stripe.com/docs/testing#cards" target="_blank">Stripe test card</a>
            to see it in action!
          </p>
        </div>
      </div>
      <div class="column">
        <form action="{% url 'pegasus_examples:accept_payment' %}" method="post" id="payment-form">
          {% csrf_token %}
          <label class="label" for="amount">
            Amount
          </label>
          <input name="amount" class="input" type="text" value="{{ amount }}">
          <div class="field">
            <label class="label" for="name">
              Payment Name
            </label>
            <div class="control">
              <input class="input" type="text" name="name" placeholder="My Amazing Site" id="name-input">
            </div>
            <p class="help has-text-grey">This name is just for your own records, and can be whatever you want</p>
            <div class="help is-danger" id="name-errors" role="alert"></div>
          </div>
          {% include 'stripe/components/card_element.html' %}
          <div class="field">
            <label class="checkbox">
              <input type="checkbox" name="consent" id="consent-checkbox">
              I agree to the <a href="{% url 'web:terms' %}" target="_blank">terms and conditions</a>
            </label>
            <div class="help is-danger" id="terms-errors" role="alert"></div>
          </div>
          <div class="field" style="margin-top: 1em;">
            <div class="control">
              <button class="button is-primary" id="purchase-button">Pay $25</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </section>
  {% if payments %}
    <section class="app-card">
      <h2 class="title is-size-4">My Payments</h2>
      <table class="table is-striped is-fullwidth">
        <thead>
        <tr>
          <th>Payments Name</th>
          <th>Payment Date</th>
          <th>Payment Amount</th>
        </tr>
        </thead>
        <tbody>
        {% for payment in payments %}
          <tr>
            <td>{{ payment.name }}</td>
            <td>{{ payment.created_at }}</td>
            <td>{{ payment.amount_display }}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </section>
  {% else %}
    <section class="app-card notification is-warning is-light">
      <div class="content">
        <p>
          No payments yet! Make a payment using any <a href="https://stripe.com/docs/testing#cards"
                                                       target="_blank">Stripe test card</a>
          to see the rest of the demo.
        </p>
        <p>
          Hint: you can use card number <strong>4242 4242 4242 4242</strong> and any expiration date / CVC /
          zipcode.
        </p>
      </div>
    </section>
  {% endif %}
{% endblock %}
{% block page_js %}
  <script src="{% static 'js/app-bundle.js' %}"></script>
  <script type="application/javascript">
    const Payments = SiteJS.app.Payments;
    var stripe = Stripe('{{ stripe_key }}');

    var cardElement = Payments.createCardElement(stripe);

    // Create a token or display an error when the form is submitted.
    var form = document.getElementById('payment-form');
    form.addEventListener('submit', function (event) {
      event.preventDefault();
      var hasErrors = false;
      var nameErrorElement = document.getElementById('name-errors');
      if (!document.getElementById('name-input').value) {
        nameErrorElement.textContent = 'Name is required.';
        hasErrors = true;
      } else {
        nameErrorElement.textContent = '';
      }
      var termsErrorElement = document.getElementById('terms-errors');
      if (!document.getElementById('consent-checkbox').checked) {
        termsErrorElement.textContent = 'Please agree to the terms and conditions.';
        hasErrors = true;
      } else {
        termsErrorElement.textContent = '';
      }
      if (!hasErrors) {
        var purchaseButton = document.getElementById('purchase-button');
        purchaseButton.classList.add('is-loading');
        stripe.createToken(cardElement).then(function (result) {
          if (result.error) {
            // Inform the customer that there was an error.
            Payments.showOrClearError(result.error.message);
            purchaseButton.classList.remove('is-loading');
          } else {
            // Send the token to your server.
            stripeTokenHandler(result.token);
          }
        });
      }
    });

    function stripeTokenHandler(token) {
      // Insert the token ID into the form so it gets submitted to the server
      var form = document.getElementById('payment-form');
      var hiddenInput = document.createElement('input');
      hiddenInput.setAttribute('type', 'hidden');
      hiddenInput.setAttribute('name', 'stripeToken');
      hiddenInput.setAttribute('value', token.id);
      form.appendChild(hiddenInput);
      // Submit the form
      // todo: use ajax to provide better feedback
      form.submit();
    }
  </script>
{% endblock %}